"""Add activity_logs table

Revision ID: a7ba99e61f61
Revises: 0001
Create Date: 2026-08-17 19:10:39.050246+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7ba99e61f61'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_containers_created_at'), 'containers', ['created_at'], unique=False)
    op.alter_column('currencies', 'is_base',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('currencies', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               comment='Rate to VND (base currency)',
               existing_nullable=True)
    op.alter_column('currencies', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('currencies_code_key'), 'currencies', type_='unique')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_created_at'), 'currencies', ['created_at'], unique=False)
    op.alter_column('customers', 'code',
               existing_type=sa.VARCHAR(length=40),
               comment='Stable customer code, e.g. KH-0041',
               existing_nullable=False)
    op.alter_column('customers', 'tax_code',
               existing_type=sa.VARCHAR(length=20),
               comment='MST — Mã số thuế',
               existing_nullable=True)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='Credit limit in VND',
               existing_nullable=True)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment='Odoo res.partner ID — migration only',
               existing_nullable=True)
    op.drop_constraint(op.f('customers_code_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.alter_column('export_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_export_orders_created_at'), 'export_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_orders_customs_declaration_number'), 'export_orders', ['customs_declaration_number'], unique=False)
    op.alter_column('import_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_import_orders_created_at'), 'import_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_orders_customs_declaration_number'), 'import_orders', ['customs_declaration_number'], unique=False)
    op.alter_column('import_run_rows', 'status',
               existing_type=postgresql.ENUM('ok', 'skipped', 'error', 'warning', name='row_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_run_rows', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='[{level, code, message}]',
               existing_nullable=True)
    op.alter_column('import_run_rows', 'entity_id',
               existing_type=sa.UUID(),
               comment='ID of created/updated entity — NULL if skipped or error',
               existing_nullable=True)
    op.alter_column('import_runs', 'source_file',
               existing_type=sa.VARCHAR(length=500),
               comment='Original filename or path',
               existing_nullable=True)
    op.alter_column('import_runs', 'source_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 of source file for dedup detection',
               existing_nullable=True)
    op.alter_column('import_runs', 'status',
               existing_type=postgresql.ENUM('running', 'completed', 'failed', 'rolled_back', 'partial', name='import_run_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_runs', 'total_rows',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_runs', 'imported_rows',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_runs', 'skipped_rows',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_runs', 'error_rows',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_runs', 'warning_rows',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_runs', 'error_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Top-level error messages for the run',
               existing_nullable=True)
    op.alter_column('payment_terms', 'days_due',
               existing_type=sa.INTEGER(),
               comment='Days until payment due',
               existing_nullable=True)
    op.alter_column('payment_terms', 'advance_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Advance payment percentage (0–100)',
               existing_nullable=True)
    op.alter_column('payment_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('payment_terms_name_key'), 'payment_terms', type_='unique')
    op.drop_index(op.f('ix_payment_terms_name'), table_name='payment_terms')
    op.create_index(op.f('ix_payment_terms_name'), 'payment_terms', ['name'], unique=True)
    op.create_index(op.f('ix_payment_terms_created_at'), 'payment_terms', ['created_at'], unique=False)
    op.alter_column('price_list_items', 'min_qty',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               comment='Minimum quantity for this price tier to apply',
               existing_nullable=False)
    op.alter_column('price_list_items', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment="Price in the price list's currency",
               existing_nullable=False)
    op.alter_column('price_list_items', 'source_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Original price from source file',
               existing_nullable=True)
    op.alter_column('price_list_items', 'source_currency',
               existing_type=sa.VARCHAR(length=10),
               comment='Currency code from source file',
               existing_nullable=True)
    op.create_index(op.f('ix_price_list_items_created_at'), 'price_list_items', ['created_at'], unique=False)
    op.alter_column('price_lists', 'customer_id',
               existing_type=sa.UUID(),
               comment='NULL = standard list applicable to all customers',
               existing_nullable=True)
    op.alter_column('price_lists', 'effective_to',
               existing_type=sa.DATE(),
               comment='NULL = no expiry',
               existing_nullable=True)
    op.alter_column('price_lists', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_price_lists_created_at'), 'price_lists', ['created_at'], unique=False)
    op.alter_column('product_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('product_categories_code_key'), 'product_categories', type_='unique')
    op.drop_index(op.f('ix_product_categories_code'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_code'), 'product_categories', ['code'], unique=True)
    op.create_index(op.f('ix_product_categories_created_at'), 'product_categories', ['created_at'], unique=False)
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=80),
               comment='Stable business code — use as upsert key. Example: HH-2041',
               existing_nullable=False)
    op.alter_column('products', 'product_type',
               existing_type=postgresql.ENUM('product', 'consumable', 'service', name='product_type'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'uom_id',
               existing_type=sa.UUID(),
               comment='Sale / stock unit',
               existing_nullable=True)
    op.alter_column('products', 'purchase_uom_id',
               existing_type=sa.UUID(),
               comment='Purchase unit (may differ from sale unit)',
               existing_nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Cost/COGS price in VND',
               existing_nullable=True)
    op.alter_column('products', 'min_stock',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Reorder point / alert threshold',
               existing_nullable=True)
    op.alter_column('products', 'max_stock',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Maximum target stock level',
               existing_nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment='Odoo product.template ID — migration only',
               existing_nullable=True)
    op.drop_constraint(op.f('products_code_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.alter_column('purchase_order_items', 'line_no',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'qty_received',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'confirmed', 'processing', 'shipping', 'completed', 'cancelled', 'returned', name='order_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_orders', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'partial', 'paid', 'overdue', 'refunded', name='payment_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('purchase_orders', 'amount_paid',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('purchase_orders', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment='Odoo purchase.order ID — migration only',
               existing_nullable=True)
    op.drop_constraint(op.f('purchase_orders_order_number_key'), 'purchase_orders', type_='unique')
    op.drop_index(op.f('ix_purchase_orders_order_number'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_order_number'), 'purchase_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_orders_payment_status'), 'purchase_orders', ['payment_status'], unique=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.alter_column('sales_order_items', 'line_no',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_order_items', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'confirmed', 'processing', 'shipping', 'completed', 'cancelled', 'returned', name='order_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_orders', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'partial', 'paid', 'overdue', 'refunded', name='payment_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales_orders', 'amount_paid',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales_orders', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment='Odoo sale.order ID — migration only',
               existing_nullable=True)
    op.drop_constraint(op.f('sales_orders_order_number_key'), 'sales_orders', type_='unique')
    op.drop_index(op.f('ix_sales_orders_order_number'), table_name='sales_orders')
    op.create_index(op.f('ix_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_sales_orders_created_at'), 'sales_orders', ['created_at'], unique=False)
    op.alter_column('shipments', 'shipment_type',
               existing_type=postgresql.ENUM('import', 'export', 'both', name='shipment_type'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=postgresql.ENUM('booking', 'loading', 'in_transit', 'arrived', 'customs', 'warehoused', 'completed', 'cancelled', name='shipment_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('shipments_shipment_number_key'), 'shipments', type_='unique')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.alter_column('staging_products', 'raw_extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Any extra columns not explicitly mapped',
               existing_nullable=True)
    op.alter_column('staging_products', 'mapped_cost_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('staging_products', 'mapped_list_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('staging_products', 'validation_status',
               existing_type=postgresql.ENUM('pending', 'valid', 'invalid', name='validation_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('staging_products', 'validation_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='[{level, code, field, message}]',
               existing_nullable=True)
    op.alter_column('stock_balances', 'qty_on_hand',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('stock_balances_product_id_location_id_key'), 'stock_balances', type_='unique')
    op.create_unique_constraint('uq_stock_balance_product_location', 'stock_balances', ['product_id', 'location_id'])
    op.alter_column('stock_movements', 'reference',
               existing_type=sa.VARCHAR(length=100),
               comment='Human-readable reference: SO-2408-0134, PO-2408-0047, etc.',
               existing_nullable=True)
    op.alter_column('stock_movements', 'reference_id',
               existing_type=sa.UUID(),
               comment='FK to the originating order/shipment (not enforced by DB constraint)',
               existing_nullable=True)
    op.alter_column('stock_movements', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Always positive. Direction determined by from/to locations.',
               existing_nullable=False)
    op.alter_column('stock_movements', 'cost_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='Unit cost at time of movement (VND)',
               existing_nullable=True)
    op.alter_column('stock_movements', 'moved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Business date/time of the stock movement',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'code',
               existing_type=sa.VARCHAR(length=40),
               comment='Stable supplier code, e.g. NCC-0012',
               existing_nullable=False)
    op.alter_column('suppliers', 'tax_code',
               existing_type=sa.VARCHAR(length=30),
               comment='VAT / GST / MST of supplier',
               existing_nullable=True)
    op.alter_column('suppliers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('suppliers', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment='Odoo res.partner ID — migration only',
               existing_nullable=True)
    op.drop_constraint(op.f('suppliers_code_key'), 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.alter_column('units_of_measure', 'factor',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('units_of_measure', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('units_of_measure_name_key'), 'units_of_measure', type_='unique')
    op.drop_index(op.f('ix_units_of_measure_name'), table_name='units_of_measure')
    op.create_index(op.f('ix_units_of_measure_name'), 'units_of_measure', ['name'], unique=True)
    op.create_index(op.f('ix_units_of_measure_created_at'), 'units_of_measure', ['created_at'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.alter_column('warehouse_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('warehouse_locations_code_key'), 'warehouse_locations', type_='unique')
    op.drop_index(op.f('ix_warehouse_locations_code'), table_name='warehouse_locations')
    op.create_index(op.f('ix_warehouse_locations_code'), 'warehouse_locations', ['code'], unique=True)
    op.create_index(op.f('ix_warehouse_locations_created_at'), 'warehouse_locations', ['created_at'], unique=False)
    op.alter_column('warehouses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('warehouses_code_key'), 'warehouses', type_='unique')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_created_at'), 'warehouses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_created_at'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    op.create_unique_constraint(op.f('warehouses_code_key'), 'warehouses', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('warehouses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_warehouse_locations_created_at'), table_name='warehouse_locations')
    op.drop_index(op.f('ix_warehouse_locations_code'), table_name='warehouse_locations')
    op.create_index(op.f('ix_warehouse_locations_code'), 'warehouse_locations', ['code'], unique=False)
    op.create_unique_constraint(op.f('warehouse_locations_code_key'), 'warehouse_locations', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('warehouse_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_units_of_measure_created_at'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_name'), table_name='units_of_measure')
    op.create_index(op.f('ix_units_of_measure_name'), 'units_of_measure', ['name'], unique=False)
    op.create_unique_constraint(op.f('units_of_measure_name_key'), 'units_of_measure', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('units_of_measure', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('units_of_measure', 'factor',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=False)
    op.create_unique_constraint(op.f('suppliers_code_key'), 'suppliers', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('suppliers', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Odoo res.partner ID — migration only',
               existing_nullable=True)
    op.alter_column('suppliers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('suppliers', 'tax_code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='VAT / GST / MST of supplier',
               existing_nullable=True)
    op.alter_column('suppliers', 'code',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Stable supplier code, e.g. NCC-0012',
               existing_nullable=False)
    op.alter_column('stock_movements', 'moved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Business date/time of the stock movement',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_movements', 'cost_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Unit cost at time of movement (VND)',
               existing_nullable=True)
    op.alter_column('stock_movements', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Always positive. Direction determined by from/to locations.',
               existing_nullable=False)
    op.alter_column('stock_movements', 'reference_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to the originating order/shipment (not enforced by DB constraint)',
               existing_nullable=True)
    op.alter_column('stock_movements', 'reference',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Human-readable reference: SO-2408-0134, PO-2408-0047, etc.',
               existing_nullable=True)
    op.drop_constraint('uq_stock_balance_product_location', 'stock_balances', type_='unique')
    op.create_unique_constraint(op.f('stock_balances_product_id_location_id_key'), 'stock_balances', ['product_id', 'location_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('stock_balances', 'qty_on_hand',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('staging_products', 'validation_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='[{level, code, field, message}]',
               existing_nullable=True)
    op.alter_column('staging_products', 'validation_status',
               existing_type=postgresql.ENUM('pending', 'valid', 'invalid', name='validation_status'),
               server_default=sa.text("'pending'::validation_status"),
               existing_nullable=False)
    op.alter_column('staging_products', 'mapped_list_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('staging_products', 'mapped_cost_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('staging_products', 'raw_extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Any extra columns not explicitly mapped',
               existing_nullable=True)
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=False)
    op.create_unique_constraint(op.f('shipments_shipment_number_key'), 'shipments', ['shipment_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('shipments', 'status',
               existing_type=postgresql.ENUM('booking', 'loading', 'in_transit', 'arrived', 'customs', 'warehoused', 'completed', 'cancelled', name='shipment_status'),
               server_default=sa.text("'booking'::shipment_status"),
               existing_nullable=False)
    op.alter_column('shipments', 'shipment_type',
               existing_type=postgresql.ENUM('import', 'export', 'both', name='shipment_type'),
               server_default=sa.text("'import'::shipment_type"),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_orders_created_at'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_number'), table_name='sales_orders')
    op.create_index(op.f('ix_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=False)
    op.create_unique_constraint(op.f('sales_orders_order_number_key'), 'sales_orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('sales_orders', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Odoo sale.order ID — migration only',
               existing_nullable=True)
    op.alter_column('sales_orders', 'amount_paid',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('sales_orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('sales_orders', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'partial', 'paid', 'overdue', 'refunded', name='payment_status'),
               server_default=sa.text("'unpaid'::payment_status"),
               existing_nullable=False)
    op.alter_column('sales_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'confirmed', 'processing', 'shipping', 'completed', 'cancelled', 'returned', name='order_status'),
               server_default=sa.text("'draft'::order_status"),
               existing_nullable=False)
    op.alter_column('sales_order_items', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sales_order_items', 'line_no',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_purchase_orders_payment_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_at'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_order_number'), table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_order_number'), 'purchase_orders', ['order_number'], unique=False)
    op.create_unique_constraint(op.f('purchase_orders_order_number_key'), 'purchase_orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('purchase_orders', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Odoo purchase.order ID — migration only',
               existing_nullable=True)
    op.alter_column('purchase_orders', 'amount_paid',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'partial', 'paid', 'overdue', 'refunded', name='payment_status'),
               server_default=sa.text("'unpaid'::payment_status"),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'confirmed', 'processing', 'shipping', 'completed', 'cancelled', 'returned', name='order_status'),
               server_default=sa.text("'draft'::order_status"),
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'qty_received',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'line_no',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_unique_constraint(op.f('products_code_key'), 'products', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Odoo product.template ID — migration only',
               existing_nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('products', 'max_stock',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Maximum target stock level',
               existing_nullable=True)
    op.alter_column('products', 'min_stock',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Reorder point / alert threshold',
               existing_nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Cost/COGS price in VND',
               existing_nullable=True)
    op.alter_column('products', 'purchase_uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Purchase unit (may differ from sale unit)',
               existing_nullable=True)
    op.alter_column('products', 'uom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Sale / stock unit',
               existing_nullable=True)
    op.alter_column('products', 'product_type',
               existing_type=postgresql.ENUM('product', 'consumable', 'service', name='product_type'),
               server_default=sa.text("'product'::product_type"),
               existing_nullable=False)
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=80),
               comment=None,
               existing_comment='Stable business code — use as upsert key. Example: HH-2041',
               existing_nullable=False)
    op.drop_index(op.f('ix_product_categories_created_at'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_code'), table_name='product_categories')
    op.create_index(op.f('ix_product_categories_code'), 'product_categories', ['code'], unique=False)
    op.create_unique_constraint(op.f('product_categories_code_key'), 'product_categories', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_price_lists_created_at'), table_name='price_lists')
    op.alter_column('price_lists', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('price_lists', 'effective_to',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='NULL = no expiry',
               existing_nullable=True)
    op.alter_column('price_lists', 'customer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = standard list applicable to all customers',
               existing_nullable=True)
    op.drop_index(op.f('ix_price_list_items_created_at'), table_name='price_list_items')
    op.alter_column('price_list_items', 'source_currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Currency code from source file',
               existing_nullable=True)
    op.alter_column('price_list_items', 'source_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='Original price from source file',
               existing_nullable=True)
    op.alter_column('price_list_items', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment="Price in the price list's currency",
               existing_nullable=False)
    op.alter_column('price_list_items', 'min_qty',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Minimum quantity for this price tier to apply',
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_terms_created_at'), table_name='payment_terms')
    op.drop_index(op.f('ix_payment_terms_name'), table_name='payment_terms')
    op.create_index(op.f('ix_payment_terms_name'), 'payment_terms', ['name'], unique=False)
    op.create_unique_constraint(op.f('payment_terms_name_key'), 'payment_terms', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('payment_terms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('payment_terms', 'advance_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Advance payment percentage (0–100)',
               existing_nullable=True)
    op.alter_column('payment_terms', 'days_due',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Days until payment due',
               existing_nullable=True)
    op.alter_column('import_runs', 'error_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Top-level error messages for the run',
               existing_nullable=True)
    op.alter_column('import_runs', 'warning_rows',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('import_runs', 'error_rows',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('import_runs', 'skipped_rows',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('import_runs', 'imported_rows',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('import_runs', 'total_rows',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('import_runs', 'status',
               existing_type=postgresql.ENUM('running', 'completed', 'failed', 'rolled_back', 'partial', name='import_run_status'),
               server_default=sa.text("'running'::import_run_status"),
               existing_nullable=False)
    op.alter_column('import_runs', 'source_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 of source file for dedup detection',
               existing_nullable=True)
    op.alter_column('import_runs', 'source_file',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Original filename or path',
               existing_nullable=True)
    op.alter_column('import_run_rows', 'entity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of created/updated entity — NULL if skipped or error',
               existing_nullable=True)
    op.alter_column('import_run_rows', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='[{level, code, message}]',
               existing_nullable=True)
    op.alter_column('import_run_rows', 'status',
               existing_type=postgresql.ENUM('ok', 'skipped', 'error', 'warning', name='row_status'),
               server_default=sa.text("'ok'::row_status"),
               existing_nullable=False)
    op.drop_index(op.f('ix_import_orders_customs_declaration_number'), table_name='import_orders')
    op.drop_index(op.f('ix_import_orders_created_at'), table_name='import_orders')
    op.alter_column('import_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_export_orders_customs_declaration_number'), table_name='export_orders')
    op.drop_index(op.f('ix_export_orders_created_at'), table_name='export_orders')
    op.alter_column('export_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=False)
    op.create_unique_constraint(op.f('customers_code_key'), 'customers', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'odoo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Odoo res.partner ID — migration only',
               existing_nullable=True)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='Credit limit in VND',
               existing_nullable=True)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'VN'::character varying"),
               existing_nullable=False)
    op.alter_column('customers', 'tax_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='MST — Mã số thuế',
               existing_nullable=True)
    op.alter_column('customers', 'code',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Stable customer code, e.g. KH-0041',
               existing_nullable=False)
    op.drop_index(op.f('ix_currencies_created_at'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=False)
    op.create_unique_constraint(op.f('currencies_code_key'), 'currencies', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('currencies', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('currencies', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               comment=None,
               existing_comment='Rate to VND (base currency)',
               existing_nullable=True)
    op.alter_column('currencies', 'is_base',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_containers_created_at'), table_name='containers')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
