"""add product excel fields

Revision ID: 9a63e90c7e70
Revises: 7c67ea17fba8
Create Date: 2026-08-21 17:48:18.284239+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a63e90c7e70'
down_revision: Union[str, None] = '7c67ea17fba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_lists', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               comment='active | expired | draft | cancelled',
               existing_nullable=False)
    op.alter_column('price_lists', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_price_lists_quotation_number'), table_name='price_lists')
    op.add_column('products', sa.Column('invoice_code', sa.String(length=80), nullable=True, comment='Mã xuất HĐ'))
    op.add_column('products', sa.Column('qr_code', sa.String(length=100), nullable=True, comment='Mã QR CODE'))
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=80),
               comment='Stable business code — use as upsert key. Example: HH-2041 (Mã hàng mới)',
               existing_comment='Stable business code — use as upsert key. Example: HH-2041',
               existing_nullable=False)
    op.alter_column('products', 'old_code',
               existing_type=sa.VARCHAR(length=80),
               comment='Mã hàng cũ',
               existing_nullable=True)
    op.alter_column('products', 'specifications',
               existing_type=sa.TEXT(),
               comment='Thông tin sản phẩm chi tiết',
               existing_nullable=True)
    op.create_index(op.f('ix_products_invoice_code'), 'products', ['invoice_code'], unique=False)
    op.create_index(op.f('ix_products_qr_code'), 'products', ['qr_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_qr_code'), table_name='products')
    op.drop_index(op.f('ix_products_invoice_code'), table_name='products')
    op.alter_column('products', 'specifications',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Thông tin sản phẩm chi tiết',
               existing_nullable=True)
    op.alter_column('products', 'old_code',
               existing_type=sa.VARCHAR(length=80),
               comment=None,
               existing_comment='Mã hàng cũ',
               existing_nullable=True)
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=80),
               comment='Stable business code — use as upsert key. Example: HH-2041',
               existing_comment='Stable business code — use as upsert key. Example: HH-2041 (Mã hàng mới)',
               existing_nullable=False)
    op.drop_column('products', 'qr_code')
    op.drop_column('products', 'invoice_code')
    op.create_index(op.f('ix_price_lists_quotation_number'), 'price_lists', ['quotation_number'], unique=False)
    op.alter_column('price_lists', 'code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('price_lists', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | expired | draft | cancelled',
               existing_nullable=False)
    # ### end Alembic commands ###
